type User {
  _id: ID
  username: String!
  email: String!
  password: String!
  profileImg: String
  dateJoined: String
  favorites: [Post]
}

type Post {
  _id: ID
  title: String!
  imageURL: String!
  categories: [String]!
  description: String!
  createdDate: String
  likes: Int
  createdBy: User!
  messages: [Message]
}

type Message {
  _id: ID
  messageBody: String!
  messageDate: String
  messageUser: User!
}

type Query {
  getPosts: [Post]
}

type Mutation {
  addPost(title: String!, imageURL: String!, categories: [String]!, description: String!, createrId: ID!): Post!
  register(username: String!, email: String!, password: String!): User!
}